apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mate-server
  namespace: mateapp
  labels:
    app: mate-server
spec:
  selector:
    matchLabels:
      app: mate-server
  template:
    metadata:
      labels:
        app: mate-server
    spec:
      containers:
        - name: mate-server
          image: busyboxplus:curl
          command:
          - "while"
          - "do"
          - "sleep 5"
          - "curl http://todoapp-service.mateapp.svc.cluster.local/api/health"
          - "done"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 80
              hostPort: 30008
